export function conflictError(){
  return {
    name: "ConflictError",
    message: "User already exists!",
  };
}